name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: EasyDesk/job-nuget-library-deploy@v1
        with:
          # (Required) The dotnet version version to be used.
          dotnet-version: '6.x'

          # (Required) The API key used to authenticate the upload of the package.
          # Can be generated via the NuGet portal.
          nuget-api-key: ${{secrets.NUGET_API_KEY}}

          # (Optional) The URL to the NuGet source where packages will be uploaded.
          # If not specified, defaults to nuget.org (https://api.nuget.org/v3/index.json).
          nuget-url: https://api.nuget.org/v3/index.json

          # (Optional) A directory where all your .nupkg files are located.
          # If not specified, defaults to the current directory.
          # publish-dir: '<your-publish-directory>'